AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'lib/tasks/**/*'
  Exclude:
    - Gemfile*
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/**/*'
  Rails:
    Enabled: true

# We don't care about method length, since we check method cyclomatic
# complexity.
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

# Trailing commas make for clearer diffs because the last line won't appear
# to have been changed, as it would if it lacked a comma and had one added.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    '%w': '[]'
    '%W': '[]'

# Whether `and` and `or` are banned only in conditionals (conditionals)
# or completely (always).
# They read better, more like normal English.
Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'

# Most classes and methods are self documenting using Rails conventions
# so don't require inline documentation
Style/Documentation:
  Enabled: false

# Using has_and_belongs_to_many is simpler when we don't need to access
# or manipulate the relationship, itself
Rails/HasAndBelongsToMany:
  Enabled: false
