---
- "American Sign Language\r\n"
- "Amharic\r\n"
- "Arabic\r\n"
- "Armenian\r\n"
- "Assyrian\r\n"
- "Burmese\r\n"
- "Cambodian\r\n"
- "Cantonese\r\n"
- "Chinese\r\n"
- "Croatian\r\n"
- "Dutch\r\n"
- "English\r\n"
- "Farsi\r\n"
- "French\r\n"
- "German\r\n"
- Greek
- Guamanian
- Gujarati
- Hebrew
- Hindi
- Hmong
- Hungarian
- Ilocano
- Indonesian
- Italian
- Japanese
- Khmu
- Korean
- Lahu
- Lao
- Mandarin
- Marshallese
- Mien
- Mixteco
- Mongolian
- OTHER
- Pashto
- Polish
- Portuguese
- Punjabi
- Rumanian
- Russian
- "Samoan\r\n"
- Serbian
- Singalese
- Spanish
- Tagalog
- Taiwanese
- Thai
- Tongan
- Turkish
- Urdu
- Vietnamese
- Visayan
